originjs/vite-plugin-federation

packages/lib/src/exposes.ts, packages/lib/src/public.ts, packages/lib/src/remotes.ts
fix style bug when build.minify true
=> fix: fix style bug when build.minify true

.eslintrc.js, packages/lib/src/shared.ts, packages/lib/src/utils.ts, yarn.lock
transform manualChunk function to manualChunks array to fix export rename bug and circular dependency(circular dependency will has problem few case)
=> fix: rename export name bug and circular dependency problems

packages/lib/src/index.ts, packages/lib/src/shared.ts
=> feat: use __rf_fn__import to replace more shared code in exposes

packages/lib/src/shared.ts
Reverts originjs/vite-plugin-federation#64
=> Revert "fix: import path error"

packages/lib/src/exposes.ts
=> fix: get css file path error

README-zh.md, README.md
=> feat: update doc

packages/lib/src/remotes.ts
=> fix: dynamic import incorrectly judged as remote component

packages/lib/src/dev/remote-development.ts
=> fix: federation will override vite `config.optimizeDeps`

packages/lib/src/index.ts, packages/lib/src/prod/expose-production.ts, packages/lib/src/prod/shared-production.ts
=> optimize: auto load the css of remote's dependencies

packages/lib/src/prod/shared-production.ts
add generateBundle hook to sharedPlugin, to transform the shared function of remotes' dependencies through find out the related chunks and transform them with logic like what renderChunk hook do
@ruleeeer
=> fix: #147 task2

package.json, packages/lib/__tests__/utils.spec.ts, packages/lib/src/index.ts, packages/lib/src/prod/expose-production.ts, packages/lib/src/prod/remote-production.ts, packages/lib/src/prod/shared-production.ts, packages/lib/src/utils/index.ts, packages/lib/types/index.d.ts
=> fix: share names with special characters fail to integrate with webpack

.github/workflows/publish.yml
=> ci: remove read-all in publish.yml

.husky/pre-commit, README-zh.md, README.md, package.json, packages/examples/vue3-demo-esm/layout/vite.config.ts, packages/lib/src/utils/index.ts, packages/lib/types/index.d.ts, pnpm-lock.yaml
1、Add externalType to specify the type of external
2、Add the doc of the demo
=> add externalType and dynamic url demo

package.json, packages/examples/vue3-demo-esm/home/src/components/Content.vue, packages/examples/vue3-demo-esm/layout/src/main.js, packages/examples/vue3-demo-esm/layout/src/store.js, packages/lib/src/dev/remote-development.ts, packages/lib/src/prod/expose-production.ts, packages/lib/src/prod/remote-production.ts
support for export from remote
e.g
a.js
``` js
export {name} from 'remotes/xxx'
```
b.js
``` js
import {name} from 'a.js'
console.log(name)
```
close #153
=> support export from remote

README.md
It broke the code highlightning
=> Add missing single quote to one of the samples

packages/examples/basic-host-remote/rollup-host/package.json, packages/examples/basic-host-remote/rollup-remote/package.json, packages/examples/simple-react-esm/host-esm/package.json, packages/examples/simple-react-esm/remote-esm/package.json, packages/examples/simple-react-systemjs/host-systemjs/package.json, packages/examples/simple-react-systemjs/remote-systemjs/package.json, packages/examples/simple-react-webpack/host/package.json, packages/examples/vitestGlobalSetup.ts, packages/lib/package.json, packages/lib/src/prod/expose-production.ts, pnpm-lock.yaml
=> feat: support rollup v3.0

.github/ISSUE_TEMPLATE/bug-report.md, packages/examples/vue3-demo-webpack-esm-esm/layout/vite.config.ts, packages/lib/src/utils/index.ts, packages/lib/types/index.d.ts
=> fix: exposes with object values

.github/workflows/publish.yml, package.json
=> fix: publish ci failed

packages/lib/src/dev/remote-development.ts
=> fix: viteDevServer may be undefined in Nuxt

packages/lib/src/utils/index.ts
=> fix: wrong version of shared lib

packages/lib/src/prod/shared-production.ts
=> feat: remove invalid import and optimize shared replace

packages/lib/src/prod/expose-production.ts
=> fix: the style is missing

README-zh.md, README.md
add star history into README
<br>
=> docs: add star history into README

packages/examples/vitestSetup.ts, packages/examples/vue3-demo-systemjs/__tests__/vue3-demo-systemjs.spec.ts, packages/lib/README.md
override vitest env to 'production'
---
=> ci: fix vue3-demo-systemjs ci error

packages/lib/__tests__/utils.spec.ts, packages/lib/src/dev/expose-development.ts, packages/lib/src/dev/remote-development.ts, packages/lib/src/dev/shared-development.ts, packages/lib/src/index.ts, packages/lib/src/prod/expose-production.ts, packages/lib/src/prod/remote-production.ts, packages/lib/src/prod/shared-production.ts, packages/lib/src/public.ts, packages/lib/src/utils/index.ts, packages/lib/src/utils/semver/compare.ts, packages/lib/src/utils/semver/constants.ts, packages/lib/src/utils/semver/index.ts, packages/lib/src/utils/semver/parser.ts, packages/lib/src/utils/semver/utils.ts
=> docs: add copyright

packages/examples/vue3-demo-esm-shared-store/remote-A/vite.config.ts, packages/examples/vue3-demo-esm-shared-store/remote-B/vite.config.ts, packages/examples/vue3-demo-systemjs/__tests__/vue3-demo-systemjs.spec.ts, packages/lib/src/prod/shared-production.ts
when using `yarn workspace`, the wrong `package.json` path may be read
fix #226
=> fix: got the wrong package.json file path in build mode

README-zh.md, packages/lib/src/prod/remote-production.ts, pnpm-lock.yaml
=> feat: throw error when exposes.import is invalid

packages/lib/src/dev/remote-development.ts, packages/lib/src/prod/remote-production.ts
=> refactor: remove unused params

README.md
Provide a link to the `vite` + `react` example in the README.
---
=> Add link to vite+react example in the README

packages/examples/react-vite/README.md, packages/examples/simple-react-esm/README.md, packages/examples/simple-react-esm/package.json
I was trying to run the examples locally and got tripped up by a few minor typos / details. This is a PR to fix them.
---
=> doc: Ntomlin/example readme updates

packages/lib/src/prod/expose-production.ts, packages/lib/src/prod/remote-production.ts, packages/lib/src/prod/shared-production.ts
=> fix: expose the module error which is under node_modules

packages/lib/src/dev/remote-development.ts
=> fix: wrong shared url is generated when server.origin is configured dev mode

README-zh.md, README.md
Supplementary instructions on how to add test example projects
=> test: how to add a test example project

.github/workflows/publish.yml, .github/workflows/scorecards.yml
=> ci: upgrade scorecard-action version

packages/lib/src/dev/remote-development.ts
[issue link](https://github.com/originjs/vite-plugin-federation/issues/416)
=> fix: monorepo source dependency not found

packages/examples/webpack-host/host/package.json, packages/examples/webpack-host/remote/package.json
=> fix: publish to npm failed because of name conflicts

packages/lib/src/prod/expose-production.ts
=> fix: throw error when remote module can not find

packages/lib/src/prod/remote-production.ts
fixes #543
Use shared modules in the list of third-party modules, if available
---
=> fix: global shared modules into wrapper

packages/lib/src/prod/shared-production.ts
This fixes #556. Tests every shared item using every regex.
---
=> fix: check for regex in external

.github/workflows/ci.yml, packages/examples/vitestSetup-serve.ts, vitest.config.ts
=> fix: remove macos ci test temporary

packages/lib/CHANGELOG.md, packages/lib/package.json
=> release: 1.3.6

packages/lib/CHANGELOG.md, packages/lib/package.json, pnpm-lock.yaml
=> release: 1.3.7

.github/workflows/ci.yml, .github/workflows/publish.yml
=> fix: ci pnpm failed

.github/workflows/publish.yml
=> fix: remove server test when publish

packages/lib/CHANGELOG.md, packages/lib/package.json
=> release: 1.3.8

packages/lib/CHANGELOG.md, packages/lib/package.json
=> release: 1.4.0

packages/lib/CHANGELOG.md, packages/lib/package.json
=> release: 1.4.1

README-zh.md
This PR updates the `README-zh.md` documentation to include an explanation for the `<link rel="modulepreload">` directive.
It describes how `modulepreload` works in modern browsers, its impact on performance for ESM-based projects, and how it's utilized in tools like Vite. This provides developers with more clarity on native module loading optimizations.
---
=> docs: update README-zh.md to include modulePreload explanation
