originjs/vite-plugin-federation

- packages/lib/src/prod/shared-production.ts
This PR is about skip the non existing dependency priority.
For example, we have those packages' dependencies like this
```
axios: {},
react: {},
lodash: {},
my-package: { react: {}, lodash: {} },
```
Our `orderByDepCount` will be like this
```
orderByDepCount: [
Map(3): { axios, react, lodash }, // those packages do not depend on any package
undefined, // this is empty item because no package has `value.size` is 1
Map(1): { my-package }, // package my-package depend on react and lodash, the value.size will be 2
]
```
Because there is no package's dependencies with size 1.
So we can filter the `orderByDepCount` element to remove undefined/empty item, or skip the empty item like this one
> skip non existing dependency priority

- packages/lib/src/prod/shared-production.ts
this pr will remove some rollup generated empty import,Just like the following
These parts cause shared to fail because both shared and local dependencies are loaded and can be removed by tweaking the rollup configuration [output.hoistTransitiveImports](https://rollupjs.org/guide/en/#outputhoisttransitiveimports)
more information about those import: [Why do additional imports turn up in my entry chunks when code-splitting](https://rollupjs.org/guide/en/#why-do-additional-imports-turn-up-in-my-entry-chunks-when-code-splitting)
> feat: remove rollup generated empty import(import 'filename.js')

- packages/lib/__tests__/semver.spec.ts
- packages/lib/src/utils/semver/compare.ts
- packages/lib/src/utils/semver/index.ts
- packages/lib/src/utils/semver/utils.ts
fix semver logic when checking `x range` (`*` and `x`) and add pre-release logic checker
> fix semver and add pre-release checker

- .github/workflows/ci.yml
- packages/lib/__tests__/semver.spec.ts
- packages/lib/__tests__/utils.spec.ts
- packages/lib/rollup.config.js
- packages/lib/src/dev/remote-development.ts
- packages/lib/src/prod/expose-production.ts
- packages/lib/src/prod/remote-production.ts
- packages/lib/src/prod/shared-production.ts
- packages/lib/src/utils/semver/compare.ts
- packages/lib/src/utils/semver/constants.ts
- packages/lib/src/utils/semver/index.ts
- packages/lib/src/utils/semver/parser.ts
- packages/lib/src/utils/semver/utils.ts
When `rollup` can't parse some monoRepo in shared, such as `primevue`, the root package.json doesn't specify main and export fields, so it will report an error, like the following configuration 
``` javascript
shared:['vue','primevue']
```
try to switch to 
``` javascript
shared:['vue' ,'primevue/button','primevue/dialog'.... ... and so on]
```
this configuration is working, but it will cause the shared configuration to be too large, so with this PR, this PR will now automatically traverse the folders under primevue for parsing after submission, generating a chunk for each repository under monoRepo, so if you are just using a component, it is recommended to use `shared:['vue','primevue/button']` for manual configuration, and `shared:['vue','primevue']` for extensive use of components
> shared support monoRepo

- packages/lib/package.json
- packages/lib/src/dev/expose-development.ts
- packages/lib/src/dev/remote-development.ts
- packages/lib/src/dev/shared-development.ts
- packages/lib/src/index.ts
- packages/lib/src/prod/expose-production.ts
- packages/lib/src/prod/remote-production.ts
- packages/lib/src/prod/shared-production.ts
- packages/lib/src/public.ts
- packages/lib/src/utils/index.ts
- packages/lib/src/utils/semver/index.ts
Vite's `mode` used to detach `Env Variable` but not development or production. 
So, add `registerPlugins` `command` support
details: https://vitejs.dev/guide/env-and-mode.html 
BTW, chore some typescript type import
> feat: add `registerPlugins` support command & chore ts

- packages/lib/src/prod/expose-production.ts
- packages/lib/src/prod/remote-production.ts
@ruleeeer hi
overwrite the id of parsedOptions.prodExpose with the one rollup resolved before exposed modules to be emited,
because of in rollup building context, rather than vite, the id of a module is using backslash(\\) instead of slash(/) in windows os
e.g.
`/path/to/a/module`
will be resolved to:
`\path\to\a\module`
this will cause some problems in finding modules like #152, so the overwriting here is ensuring the id in parsedOptions.prodExpose is synchronized with building context
[reproduction](https://github.com/originjs/vite-plugin-federation/tree/main/packages/examples/simple-react-esm)
try to build the remote-esm app(on windows os), and find out that the exposed button didn't call importShared function
> optimize: overwrite the expose's id to synchronize with building context

- packages/lib/src/prod/expose-production.ts
- packages/lib/src/prod/remote-production.ts
@ruleeeer hi!
the single quote in template of remote helper will be compiled to double quote when turn on the build.minify(=true), it made the building output lost some codes, so i change the reg exp to match double quote
[reproduction](https://github.com/Timehello/federation-test)
try to build the remote app with turning on build.minify, and you will find out that remoteEntry.js didn't import component's css
> fix: regexp of dynamic css matchs double quotes(")

- packages/lib/src/dev/remote-development.ts
- packages/lib/src/prod/remote-production.ts
- packages/lib/src/utils/index.ts
Example implementation of #157 
Adds ability to define dynamic remotes via `external: "promise new Promise(resolve => /* ... */)"` syntax.
Example:
```js
federation({
remotes: {
myRemote1: {
external: "promise new Promise(resolve => resolve(window.remoteUrls.myRemote1))",
},
myRemote2: {
external: 'promise fetch("/api/remotes/myRemote2").then(res => res.json()).then(({ url }) => url)',
},
},
})
```
I'm not sold on the API, I just based it off of Webpack's similar feature - albeit not the same, as this version does not require you to define the module shape as well (`get` / `init`).
Any suggestions as to what the API should be like, e.g.:
```js
federation({
remotes: {
myRemote1: {
// just an example name, to demo this approach
expression: "window.remoteUrls.myRemote1"
},
myRemote2: { …
```
> feat: enable dynamic remote loading

- .husky/pre-commit
- package.json
- packages/lib/src/index.ts
- packages/lib/src/prod/shared-production.ts
vite 2.9.0 updated the default `manualChunks` behavior, which caused the plugin to potentially cause shared processing to fail when used with vite 2.9.0 and above, this PR fixes the issue at vite 2.9.0 and above
<br>
close #178
> fix: vite 2.9.0 causes manualChunks failed

- packages/lib/src/prod/expose-production.ts
- packages/lib/src/prod/remote-production.ts
- packages/lib/src/public.ts
- packages/lib/src/utils/index.ts
fix #216 
Here is a pr for content hash calculate for export modules,  i update the calculate way by depend to rollup which can config the `outputh.chunkFileNames` to generate the filename rule for chunk automatically
---
> fix: update content hash calculate for export modules

- README.md
This PR removes the unwanted space in the link to `await` MDN documentation.
> Fix `await` link to MDN

- packages/lib/src/prod/shared-production.ts
For some reasons, after build, I received the `index.<hash>.js` file content like this one
```
import {importShared} from './__federation_fn_import.js'
const {default:I,r:d} = await importShared('react')
const {r:be} = await importShared('react-dom')
const {j:u,a:O,F:Ce,useLocation:K,matchRoutes:xe,Outlet:Pe,Navigate:Oe,useNavigate:qe,Routes:Se,Route:L,BrowserRouter:Ae} = await importShared('react-router-dom')
import{P as Fe,a as Me,t as De,F as Re,L as se,A as we,R as Ie,d as re,r as Qe,n as x,b as Ee,g as Te,c as $e,e as v,i as _,f as _e,S as ie,h as ne,p as S,m as j,M as Ue,j as V,k as W,o as z,l as Le,q as U,s as w,u as G,v as ke,w as Ke,x as Be,y as Ne,z as Z,B as He,C as je,D as Ve,Q as We,App as ze}from"./__federation_expose_App.7d6c791a.js";const …
```
> fix: importShared is not a function

- packages/lib/src/dev/remote-development.ts
As a developper and during development, i need vite-plugin-federation resolve my specific host origin set on vite configuration server.origin  Use it or try to set localhost.
In a specific configuration (dnsmasq & docker) to reproduce "real" production state, i wasnt able to define a different hostname for our .cacheDir path, after looking into the repo code, find that we can use origin option from vite config server.
This PR is an open discussion first, i am not sure server.origin in this way is the best solution, but let's discuss on it.!
---
> feat(resolveHostname) resolve host name and respect server.origin

- packages/lib/src/dev/remote-development.ts
- packages/lib/src/prod/remote-production.ts
When federated module fails to load, promise returned from import(...) is never rejected.
This PR allows to handle import errors in host application by using catch, and present errors to the user. 
This fixes #316.
> fix: added catch when loading js with import(...)

- packages/lib/src/prod/remote-production.ts
Solves the default + named import case, i.e.
```ts
import React, {useState} from 'react
```
https://github.com/originjs/vite-plugin-federation/issues/294
---
> fix default and named import case

- packages/lib/src/prod/remote-production.ts
`fix #355`
generate correct source_map when use remote code.
- [X ] Bug fix
> fix: generate correct source_map when use remote code

- README-zh.md
- README.md
- packages/lib/src/dev/remote-development.ts
- packages/lib/src/utils/index.ts
- packages/lib/types/index.d.ts
fix dev mode error because the ast parse occurred for non-js-related file types.
Now transform hook will only process the following types of files by default.
`['.js','.ts','.jsx','.tsx','.mjs','.cjs','.vue','.svelte']`
If you need to deal with other types, you can add other types to the federation configuration to support it like follow
``` js
federation({
transformFileTypes:['.myCustomized']
})
```
---
- [ x] Bug fix
> fix: dev mode error because of not js type related files

- .github/PULL_REQUEST_TEMPLATE.md
The current PR template includes a link to https://github.com/originjs/vite-plugin-federation/blob/main/CONTRIBUTING.md which 404's. This removes it. I looked for an appropriate replacement but did not find one.
---
> chore: Remove dead link to contributing guidelines

- packages/lib/src/index.ts
Currently vite mode is always overriding plugin configuration.
Changed to use configured mode, and if absent default to vite mode.
fix for originjs/vite-plugin-federation#404
> fix: vite --mode always overrides configured mode

- packages/lib/src/dev/remote-development.ts
dev mode, running host without localhost cause remote importing shared failed
Dev mode, if hosting without **host**, but ip like **192.168.1.XX**, 
shared address generated in virtual file `virtual:__federation__` will be something like
```js
return {
'shared-lib':{'undefined':{get:()=> get('http://localhost:port/node_modules/shared-lib.js', remoteFrom)}}
}
}
```
The host is hard coded to **localhost**, which will cause the remote importing shared failed
```js
get('http://localhost:port/node_modules/shared-lib.js
```
changes to
```js
get(window.location.origin+'/node_modules/shared-lib.js
```
> dev mode, running host without localhost cause remote importing shared failed V2

- packages/lib/src/prod/federation_fn_import.js
[issue link](https://github.com/originjs/vite-plugin-federation/issues/413)
update:
```ts
if (module.default)
module = module.default
```
to
```ts
if (module.default && Object.keys(module).length < 2)
module = module.default
```
> fix: improve getSharedFromXXX detect need unwrap module V2

- packages/lib/src/dev/remote-development.ts
Stop reading server configuration when no shared on configuration
When we launch build in development mode, the code tries to read the configuration of the development Vite server, but there is no such configuration, producing an error because configureServer is not called in this mode.
---
> fix: stop reading server configuration when no shared

- packages/lib/src/dev/remote-development.ts
- packages/lib/src/index.ts
- packages/lib/src/prod/expose-production.ts
- packages/lib/src/prod/remote-production.ts
- packages/lib/src/public.ts
插件很好用，能满足从远程读取页面或者插件的能力。我们目前项目非常的大，**每次打包都会花费非常非常多的时间**，因此我们就想引入此插件来优化打包时间，我们的想法是，**第一次打包时**，将页面和部分组件都打成federation包，同时把引用这些包的地方都改为远程引入地址。这样当我们之后只改动页面或者组件时，我们只需要打包这一部分包就可以**实现按需打包**，大大的降低打包时间。可惜的是此插件不支持这个能力，因为支持这个能力的条件是能有多个federation配置（因为项目必须得同时导出和引入，且有多个exposes配置，之后打包时按需执行其中某一个exposes），所以基于此需求，我对此插件进行了一些修改，可以使其满足这个需求。
**多federation配置项目演示：**
https://github.com/amazingywk/vite-multiple-federation-example
注：因为必须得打成包才可以使用，这里可以看到我把它打成了自己的包@amazingywk/vite-plugin-federation@1.0.1，这个包的代码与我提的此pr代码一致
**不能写多个包含remotes的federation配置**
尽管我已经尽力满足了可以写多个federation配置，但仍然还有这一个小问题没有解决，但是在我看来，这个问题是允许存在的，也不会有很大的影响，且以我的能力（刚工作一年的菜鸟）看来这个问题想要修改可能会导致很多逻辑的重构。也希望大大们后续可以解决这个问题，感谢
---
> feat: 插件支持多个federation配置

- packages/lib/src/prod/federation_fn_import.js
This PR is relevant to the issues #498 and #499 .
The shared import is only checking if there are less than 2 properties available on the module. This check is not sufficent. For instance, React has mor than 1 export but is still relying on the default export. This breaks a React application when used as a shared library. 
This happens since the change was introduced 1.3.1
My proposel is to flatten the default export and add all module exports as well. 
This is still better than just ignore either default exports or all other exports but has of course the caveat is that some default exports get overwritten. But in the current solution there wouldn't be any exports to be overwritten anyway.
---
> fix: Flatten module with default exports when available

- packages/lib/src/prod/shared-production.ts
After https://github.com/originjs/vite-plugin-federation/pull/487, `__federation_fn_import.js` was left without a content hash. With this pull request it will be named like `__federation_fn_import-d6086ec8.js`.
---
> feat: add content hash to federation_fn_import file name

- packages/lib/src/prod/federation_fn_import.js
remote client use shared module like dayjs which export default a function, will get a type error: xxx is not function
flattenModule function return object or not a function when module default  export is function
fix issue [537](https://github.com/originjs/vite-plugin-federation/issues/537)
---
> fix: flatten module return function when module default is function

- README.md
- packages/lib/__tests__/utils.spec.ts
- packages/lib/src/prod/expose-production.ts
- packages/lib/src/utils/index.ts
- packages/lib/types/index.d.ts
All styles for exposed components are always put in the \<head\> element. This is fine unless a component creates a Shadow DOM, because then the styles inside the \<head\> won't affect the contents of the Shadow DOM. That's why I added a configuration option to the plugin. When the new boolean is set to 'true', then the \<link\> element is created and instead being put in the \<head\> element, it's held in memory and put under the global 'window' object. From this point the exposed component that creates a Shadow DOM can take this \<link\> element and put it directly inside the Shadow DOM.
This PR fixes the following issue: https://github.com/originjs/vite-plugin-federation/issues/488
> feat(dev): add option for adding styles to global object instead of <head> element (for using in Shadow DOM)

- packages/lib/src/prod/shared-production.ts
chunk.filename is like '__federation_shared_cesium-4d8g9d5d.js' We need to extract package name (cesium) without the the chunk id.
---
> Fix sharedFilePathReg

- packages/lib/src/index.ts
This PR solve the issue of error during build. `npx vite build --mode development`.
The `mode` can be used for environment and not limited to the command `build` or `serve`. It can be `mode=development` but command is `build`. Switching the sequence should fix the issue.
However there will be another issue, if someone want to serve a production environment. 
`npx vite serve --mode production`. For long term solution i would suggest to remove the `mode` from the condition statement.
```
error during build:
TypeError: [originjs:federation] Cannot read properties of undefined (reading 'config')
```
fixes #527 [React: Cannot read properties of undefined (reading 'config') in devSharedScopeCode](https://github.com/originjs/vite-plugin-federation/issues/527)
---
> Fix error during build for development mode

- packages/lib/src/prod/shared-production.ts
When I was working on the remote side and using the shared features with a scoped package, as in the following example
```
shared: {
'@vue/composition-api': { generate: false }
}
```
I found that the `generate: false` setting had no effect. This is because the `shareName2Prop` map applies the `removeNonRegLetter` function to the package name `@vueComposition-api` as it's key. Therefore, when determining the `needRemoveShared` condition, we should also apply `removeNonRegLetter` to the chunk filename. This change is necessary for the program to work correctly.
---
> fix: removeNonRegLetter for chunk filename

- packages/lib/src/prod/expose-production.ts
- packages/lib/src/prod/federation_fn_import.js
- packages/lib/src/prod/remote-production.ts
- pnpm-lock.yaml
Safari currently has a bug where, if the same module is imported twice or more simultaneously, it fails with a reference error.
This is actually a Webkit bug and is registered here: https://github.com/WebKit/WebKit/pull/24122
We don't know when this bug will be fixed, but we can work around it with a simple modification that prevents the same remote module from being imported twice. This PR implements this modification.
I'm not familiar with the source code of this lib, so I altered the function `__federation_import` everywhere I found it. Please, check.
> feat: adds a workaround for a safari bug when loading modules async

- README.md
- packages/examples/vue3-demo-esm-expose-store/host/vite.config.ts
- packages/examples/vue3-demo-esm-shared-store/host/vite.config.ts
- packages/examples/vue3-demo-esm/home/vite.config.ts
- packages/examples/vue3-demo-systemjs/layout/vite.config.ts
- packages/examples/vue3-demo-webpack-esm-esm/layout/vite.config.ts
- packages/examples/vue3-demo-webpack-esm-var/layout/vite.config.ts
- packages/examples/vue3-demo-webpack-systemjs/layout/vite.config.ts
- packages/lib/src/prod/remote-production.ts
- packages/lib/src/utils/html.ts
- packages/lib/src/utils/index.ts
- packages/lib/types/index.d.ts
- pnpm-lock.yaml
if we use this plugin in a project to share a dependency, the dependency was lazy import as Promise. This approach required a certain delay if the project needed immediate access to the dependency. 
Now, with new configuration feature, the shared dependency module is now preloaded, there is no need to wait.
parts of the code were informed by Vite's internal build-html plugin.
[vite:build-html plugin](https://github.com/vitejs/vite/blob/30f256ec8c3a737c35afc186f8a77cecb68bb7ed/packages/vite/src/node/plugins/html.ts#L719)
---
> feat: the shared dependency bundle file append to html head as link modulepreload

- packages/lib/src/prod/remote-production.ts
With 'allow-extension', the build could add some additional code in files of shared librairies. But if the host embed a library, that has been extended in a remote, the remote can not access the extended code anymore.
I have seen this bug when I used
`import Lock from "@mui/icons-material/Lock";`
in a remote micro-frontend.
Some code to build the icon, `createSvgIcon` function, was added to the code of a shared library.
- [X ] Bug fix
> Fix: preserve signature of shared librairies.

- README.md
Documentation for working with `virtual:__federation__` has been added. It addresses user questions such as "how to load a module at runtime."  
https://github.com/originjs/vite-plugin-federation/issues/642  
Describes part of the changes from https://github.com/originjs/vite-plugin-federation/pull/481.
---
> docs: add runtime add remotes with virtual:__federation__

- packages/lib/src/prod/expose-production.ts
EDIT : Sorry the problem occurs since the 1.3.8 not the 1.3.7.
Since version _1.3.8_ our federated CSS files are exposed by a wrong path (under double slashes).    
For example, the same configurations of this plugin produce :  
- **1.3.6** : 
```
http://domain.com/foo/assets/__federation_expose_ModuleName-xxxx.css
```
- **1.3.8** :
```
http://domain.com/foo//assets/__federation_expose_ModuleName-xxxx.css
```
The problem come from the usage of `join('/')` while a "base" vite can end by a slash (which is mostly the case for other plugins configurations).  
The current code looks like this :  
```typescript
const baseUrl = '/foo/';
const assetsDir = 'assets';
const cssPath = 'myFile.css';
const href = [baseUrl, assetsDir, cssPath].filter(Boolean).join('/');
// href : …
```
> fix: CSS path in expose-production produce double slashes

- packages/lib/package.json
- packages/lib/src/prod/expose-production.ts
This PR fixes an issue with CSS loading in remote modules where styles were being loaded from incorrect URLs missing the hostname. Previously, when loading remote module styles, the URLs were constructed without the proper hostname (e.g. `//assets/style.css` instead of `http://hostname/assets/style.css`).
The fix improves URL construction logic by:
- Properly handling both absolute and relative base URLs
- Preserving hostname when constructing style URLs
- Adding utility functions for consistent path trimming
- Ensuring proper URL joining for remote module styles
The issue was particularly visible when:
1. Loading remote module styles in production builds
2. Using base URLs other than root ('/')
3. Working with cross-origin remote modules
---
> Fix: Ensure CSS paths include hostname for remote module styles

- packages/lib/CHANGELOG.md
> release: 1.3.9

- packages/lib/src/prod/expose-production.ts
- packages/lib/src/prod/federation_fn_import.js
> Firstly I want to thank for taking such initiative to solve this problem!
I tried using this package to create remoteEntry from vite and consume in webpack. But I was constantly facing a problem of double react getting loaded. On deep investigation I understood that the webpack in shareScope was providing 2 versions of react { 16: /**/, 18: /**/ } even though I provided required verison 18 in the federationPlugin it used to take 16 since the code assumes only one package will be coming.
I tried to fix it by
1. allow all versions to be part of __federation_shared__ so that whichever is required will be accessible
2. based on requiredVersion proper package will be provided to the scope
---
> fix: incorrect version provided to the scope when multiple versions are available

- packages/lib/src/prod/expose-production.ts
Fix bug when exposing the styles to the window
Fixing bug caused on the 1.3.7 release that broke the **dontAppendStylesToHead** flag when set to true
When running dynamicLoadingCss throws error saying cannot read name of undefined;
To test just run Module with **dontAppendStylesToHead**, set to true in the current version(1.3.9) the error happens
---
> Fix bug on expose-production.ts

- packages/lib/src/prod/expose-production.ts
This PR fixes two errors. One, simpler was introduced in this commit: https://github.com/originjs/vite-plugin-federation/commit/766b521ee56fd2ba15f234c5f5c0aa6336fa518f and it changed
`const key = 'css__${options.name}__' + exposeItemName;`
to 
`const key = 'css__' + options.name + '__' + exposeItemName;`
which causes an error, because options.name should be resolved and not passed as a string.
The second error that this PR fixes is more complicated and I didn't think about such a case, when I introduced this feature in your project for the first time here: https://github.com/originjs/vite-plugin-federation/pull/548
Multiple remote components can have the same path to a CSS file with styles, becasue they can come from the same remote application (that's actually a case we have in our …
> fix(dev): Append styles to head even for duplicates, fix key construction

- packages/lib/src/dev/remote-development.ts
> Fixes #687
